export const channels = {
  appGetInfo: "app:get-info",
  runtimeGetStatus: "runtime:get-status",
  runtimeSendMessage: "runtime:send-message",
  runtimeSubscribe: "runtime:subscribe",
  conversationsList: "conversations:list",
  conversationsLoad: "conversations:load",
  profilesList: "profiles:list",
  profilesGetCurrent: "profiles:get-current",
  profilesSetCurrent: "profiles:set-current",
  memoryList: "memory:list",
  memoryUpdate: "memory:update",
  modelsGetConfig: "models:get-config",
  skillsListInstalled: "skills:list-installed",
  skillsSearchHub: "skills:search-hub",
  skillsInstallFromHub: "skills:install-from-hub",
  skillsSetEnabled: "skills:set-enabled",
  scheduledJobsList: "scheduled-jobs:list",
  scheduledJobsCreate: "scheduled-jobs:create",
  scheduledJobsUpdate: "scheduled-jobs:update",
  scheduledJobsPause: "scheduled-jobs:pause",
  scheduledJobsResume: "scheduled-jobs:resume",
  scheduledJobsRunNow: "scheduled-jobs:run-now",
  scheduledJobsRemove: "scheduled-jobs:remove",
  spacesList: "spaces:list",
  spacesGetCurrent: "spaces:get-current",
  spacesSetCurrent: "spaces:set-current",
  spacesAdd: "spaces:add",
  spacesRemove: "spaces:remove",
  settingsGet: "settings:get",
  settingsUpdate: "settings:update"
} as const;

export type ChannelName = (typeof channels)[keyof typeof channels];
